server:
  port: 8080
  servlet:
    context-path: /community

spring:
  thymeleaf:
    # close cache
    cache: false

  # dataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: a923488302
    # 连接池配置
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 最大连接数
      maximum-pool-size: 15
      # 最小连接数
      minimum-idle: 5
      # 多久关闭一个空闲连接
      idle-timeout: 30000

mybatis-plus:
  configuration:
    # 配置日志 log-impl：日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 可将表字段由下划线变为驼峰式
    map-underscore-to-camel-case: true
  # 在xml内可省略包名
  type-aliases-package: me.xnmk.community.entity
  # 设置xml所在位置
  mapper-locations: classpath:mapper/*.xml



