server:
  port: 8080
  servlet:
    context-path: /community

spring:
  thymeleaf:
    # close cache
    cache: false

  # dataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: a923488302
    # 连接池配置
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 最大连接数
      maximum-pool-size: 15
      # 最小连接数
      minimum-idle: 5
      # 多久关闭一个空闲连接
      idle-timeout: 30000

  mail:
    host: smtp.sina.com
    port: 465
    username: xnmk_community@sina.com
    password: 5ae7175e16070fa4
    # 启用安全传输协议
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  # redis
  redis:
    host: localhost
    port: 6379
    database: 1
    connect-timeout: 1800000

  # kafka
  kafka:
    bootstrap-servers: 120.25.242.250:9093
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000

  # elasticsearch
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200

  task:
    execution:
      pool:
        max-size: 15
        core-size: 5
        queue-capacity: 100
    scheduling:
      pool:
        size: 5

  # quartz
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5

mybatis-plus:
  configuration:
    # 配置日志 log-impl：日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 可将表字段由下划线变为驼峰式
    map-underscore-to-camel-case: true
  # 在xml内可省略包名
  type-aliases-package: me.xnmk.community.entity
  # 设置xml所在位置
  mapper-locations: classpath:mapper/*.xml

# 自定义参数
community:
  path:
    domain: http://localhost:8080
    upload: d:/workSpace/data/upload
